### ISSUE TITLE
Write single page website

### ISSUE THREAD

**Issue by godber** [planetarypy/planetarypy.github.io#1]
Collect information for simple single page website.  This should have the following sections.
- PlanetaryPy Overview - contents written by me
- PlanetaryPy Projects - List of python projects, descriptions and links to documentation.
- Other Planetary Projects in Python - Links to python projects not part of planetarypy

**Comment by godber** [comment]
Make sure to include the gitter room sidecar:

```
<script>
  ((window.gitter = {}).chat = {}).options = {
    room: 'planetarypy'
  };
</script>
<script src="https://sidecar.gitter.im/dist/sidecar.v1.js" async defer></script>
```

**Comment by rbeyer** [comment]
This is a historic Issue from the early days of planetarypy, and now that we finally have a new website (with more than one page), I think we can safely close this.
